SRC = $(wildcard *.c) $(wildcard ../lib/*.c)
LIBS = ../lib/tcp_buffer.c ../lib/tcp_utils.c ../lib/thpool.c
CC = gcc
CFLAGS += -I../include -Wall -Wextra -fsanitize=address -lpthread -g

all: FS FC

FS: FS.o $(LIBS)
	$(CC) $(CFLAGS) $(LDFLAGS) $^ -o $@

FC: FC.o $(LIBS)
	$(CC) $(CFLAGS) $(LDFLAGS) $^ -o $@

include ${SRC:.c=.d}
%.o: %.c
	$(CC) $(CFLAGS) -c $< -o $@

%.d: %.c
	@set -e; rm -f $@; \
	$(CC) -M $(CFLAGS) $< > $@.$$$$; \
	sed 's,\($*\)\.o[ :]*,\1.o $@ : ,g' < $@.$$$$ > $@; \
	rm -f $@.$$$$

clean:
	rm -f *.o *.d FS FC

.PHONY: all clean
